### ISSUE TITLE
How to predict slack?

### ISSUE THREAD

**Issue by SaltyfishK423** [TimingPredict/TimingPredict#9]
Thank you for your work. And I have one question. Your paper mentions predicting slack, but your code does not provide such an operation, how do I get slack based on the predicted arrival time?

**Comment by gzz2000** [comment]
Hello. Our dataset labels provide both arrival times (AT) and required arrival times (RAT). As a result, you can compute slack at endpoints. For early slacks, slack = AT - RAT. For late slacks, slack = RAT - AT.
We did not provide this in our code because we are not satisfied with the prediction results:( It works well on some designs, but not all of them.

**Comment by SaltyfishK423** [comment]
Thank you for your reply and wish you all the best in your work.
